[package]
name = "rustserver"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2"
actix-http = "2"
actix-web = "4.0.0-beta.8" 
handlebars = { version = "4.1.0", features = ["dir_source"] }
tera = "1.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
dotenv = "0.15.0"
r2d2 = "*"
diesel = { version = "1.4", features = ["mysql", "r2d2"] }
scraper = "0.12.0"
chrono = "0.4"
unicode-segmentation = "1.8.0"
kakao-rs = "0.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
